{
  "run_id": "pipeline_run_20250914_135043",
  "timestamp": "20250914_135043",
  "current_stage": 1,
  "stage_status": "failed",
  "stage_name": "Dataset Download",
  "completed_stages": [],
  "details": {
    "error": "/home/gli/anaconda3/envs/py312/bin/python: can't open file '/home/gli/Documents/malaria_detection/download_datasets.py': [Errno 2] No such file or directory\n"
  }
}